object Versions {
  const val compose = "1.5.1"
  const val androidGradlePlugin = "8.2.1"
  const val vanniktechGradlePlugin = "0.18.0"
  const val kotlin = "1.9.0"
  const val activity = "1.4.0"
  const val material = "1.5.0"
  const val coreKtx = "1.7.0"
  const val constraintLayout = "1.0.0"
  const val appCompat = "1.4.1"
  const val coil = "1.4.0"
  const val jUnit = "4.13.2"
  const val jUnitExtensions = "1.1.3"
  const val accompanistInsets = "0.23.0"
  const val multiFab = "1.2"
  const val lifeCycle = "2.4.0"
  const val espresso = "3.4.0"
  const val ktlint = "10.2.0"
}