name: Sample Build CI
on:
  pull_request:
    branches: [ main ]

jobs:
  sample-debug-build:
    runs-on: macos-latest
    steps:
      # Code checkout
      - name: Checkout code
        id: checkout_code
        uses: actions/checkout@v4

      # Setup Android and Gradle
      - name: Job set up
        uses: ./.github/workflows/composite

      # Generate debug build
      - name: Build Android app
        id: generate_debug_build
        if: always()
        run: ./gradlew assembleDebug --stacktrace --info